controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    PD_control:
      type: rbt_pd_cnt/Rbt_PD_cnt
PD_control:
    ros__parameters:
      joint:
        - LF_HFE
        - RF_HAA
        - LF_KFE
        - RF_KFE
        - LH_HAA
        - LH_HFE
        - RH_HAA
        - RH_HFE
        - LF_HAA
        - RF_HFE
        - LH_KFE
        - RH_KFE
      init_pos:              
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0

joint_state_broadcaster:
  ros__parameters:
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
    use_sim_time: True
    interfaces:
      - position
      - velocity 
      - effort
  