controller_manager:
  ros__parameters:
    update_rate: 1000  

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    leg_forward_position_controller:
      type: position_controllers/JointGroupPositionController
    
    leg_pid_controller:
      type: ros2_pid_controller/PID_Controller

leg_forward_position_controller:
  ros__parameters:
    joints: 
    - HAA
    - HFE
    - KFE
    
    

leg_pid_controller:
  ros__parameters:
    joint: 
      - KFE
      - HFE
      - HAA
    interface_name: position
    K_i: 0.0
    K_d: 0.00001
    K_p: 0.01
    start_command: 
    - 0.0
    - 0.0 
    - 0.0

